/*
OffstageArts: Enterprise Database for Arts Organizations
This file Copyright (c) 2005-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * FrontGui.java
 *
 * Created on July 13, 2005, 10:52 PM
 */

package offstage.devel.gui;
import citibob.task.SqlTask;
import java.sql.*;
import javax.swing.*;
import java.util.prefs.*;
import citibob.swing.prefs.*;
import offstage.FrontApp;
//import offstage.EQueryBrowserApp;
import citibob.sql.*;
import offstage.cleanse.CleansePanel;
import offstage.devel.gui.*;

/**
 *
 * @author  citibob
 */
public class DevelFrame extends javax.swing.JFrame {

DevelModel dmod;
FrontApp fapp;

	/** Creates new form FrontGui */
	public DevelFrame() {
		initComponents();
	}

	public DevelPanel getDevelPanel() { return people; }
	
	public void initRuntime(SqlRun str, FrontApp xfapp) //, DevelModel xdmod)
	throws org.xml.sax.SAXException, java.io.IOException
	{
		this.fapp = xfapp;
		this.dmod = new DevelModel(fapp);

		actions.initRuntime(fapp);
		people.initRuntime(str, fapp, dmod);

//		fapp.addListener(new FrontApp.Adapter() {
//		public void screenChanged() {
//			tabs.setSelectedIndex(dmod.getScreen());
//		}});


//		// Mess with preferences
//		str.execUpdate(new UpdTasklet2() {
//		public void run(SqlRun str) throws Exception {
//			// Also set up frame preferences
//			new citibob.swing.prefs.SwingPrefs().setPrefs(DevelFrame.this, "", fapp.userRoot().node("DevelFrame"));
//		}});
	
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tabs = new javax.swing.JTabbedPane();
        actions = new offstage.devel.gui.DevelActionPanel();
        people = new offstage.devel.gui.DevelPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Development");

        tabs.addTab("Actions", actions);
        tabs.addTab("Development", people);

        getContentPane().add(tabs, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Window");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private offstage.devel.gui.DevelActionPanel actions;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private offstage.devel.gui.DevelPanel people;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables


}
