/*
OffstageArts: Enterprise Database for Arts Organizations
This file Copyright (c) 2005-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * EntityPanel.java
 *
 * Created on June 5, 2005, 9:48 AM
 */

package offstage.devel.gui;


import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import citibob.sql.*;
import citibob.jschema.*;
import citibob.jschema.swing.*;
//import citibob.jschema.swing.JSchemaWidgetTree;
import citibob.swing.table.*;
import citibob.swing.typed.*;
import java.awt.*;
import java.awt.event.*;
import offstage.FrontApp;
import offstage.devel.gui.DevelModel;
import citibob.app.*;
import offstage.datatab.DataTab;
import offstage.datatab.DataTabSet;

/**
 *
 * @author  citibob
 */
public class EntityPanel extends javax.swing.JPanel {
	
	/** Creates new form EntityPanel */
	public EntityPanel() {
		initComponents();
	}

	public void setAllBackground(Color bg)
	{
		setBackground(bg);
		mainPanel.setBackground(bg);
	}
	
	EntityPanel getThis() { return this; }
	
	public void initRuntime(SqlRun str, FrontApp fapp, DevelModel dm)
	//throws java.sql.SQLException
	{
		App app = fapp;
		mainPanel.initRuntime(str, fapp, dm);
		
		// Init the credit card panel
		TypedWidgetBinder.bindRecursive(this, mainPanel.mainRm, app.swingerMap());
		cryptCCInfo.initRuntime(fapp.keyRing());
		
		
		DataTabSet tabs = fapp.dataTabSet();
		for (DataTab tab : tabs.guiTabs) {
			tab.addToGroupPanels(str, dm, groupPanels, app.swingerMap());
		}
		
//		termsPanel.initRuntime(str, dm.getTermsSb(),
//			new String[] {"Term", "Role"},
//			new String[] {"groupid", "courserole"},
//			false, app.swingerMap());
//			termsPanel.setEnabled(false);
		
		this.cryptCCInfo.initRuntime(fapp.keyRing());
		
	}	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classesPanel = new offstage.gui.GroupPanel();
        groupPanels = new javax.swing.JTabbedPane();
        cryptCCInfo = new offstage.swing.typed.CryptCCInfo();
        mainPanel = new offstage.devel.gui.PersonPanel();

        groupPanels.setPreferredSize(new java.awt.Dimension(458, 200));
        groupPanels.addTab("Credit Card", cryptCCInfo);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(groupPanels, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(mainPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 389, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(groupPanels, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private offstage.gui.GroupPanel classesPanel;
    private offstage.swing.typed.CryptCCInfo cryptCCInfo;
    private javax.swing.JTabbedPane groupPanels;
    private offstage.devel.gui.PersonPanel mainPanel;
    // End of variables declaration//GEN-END:variables

//	public static void main(String[] args) throws Exception
//    {
//
//
//		FrontApp app = new FrontApp();
//		FullEntityDbModel dm = app.getFullEntityDm();
//		Statement st = app.getPool().checkout().createStatement();
//
//		dm.setKey(139208);
//		dm.doSelect(st);
//		System.out.println("Type = " + dm.getEntityType());
//
//		EntityPanel personPanel = new EntityPanel();
//		personPanel.initRuntime(st, dm);//personRM, dm.getPhonesSb());
//
//		
//		
//	    JFrame frame = new JFrame();
//	    frame.getContentPane().add(personPanel);
//		frame.pack();
//	    frame.setVisible(true);
//		System.out.println("Done");
//    }
	
}
