/*
OffstageArts: Enterprise Database for Arts Organizations
This file Copyright (c) 2005-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * StudentInfoPane.java
 *
 * Created on July 27, 2008, 10:02 PM
 */

package offstage.school.gui;

import citibob.sql.SqlRun;
import citibob.swing.typed.TypedWidgetBinder;
import citibob.types.KeyedModel;
import offstage.FrontApp;

/**
 *
 * @author  citibob
 */
public class DefaultStudentInfoPane extends StudentInfoPane {
	
	/** Creates new form StudentInfoPane */
	public DefaultStudentInfoPane() {
		initComponents();
	}

	public void initRuntime(SqlRun str, FrontApp fapp, SchoolModel schoolModel)
	{
		super.bindGender(gender, schoolModel);
		TypedWidgetBinder.bindRecursive(this, schoolModel.studentRm, fapp.swingerMap());
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        StudentPane = new javax.swing.JPanel();
        FirstMiddleLast2 = new javax.swing.JPanel();
        lFirst2 = new javax.swing.JLabel();
        lMiddle2 = new javax.swing.JLabel();
        lLast2 = new javax.swing.JLabel();
        salutation2 = new citibob.swing.typed.JTypedTextField();
        firstname2 = new citibob.swing.typed.JTypedTextField();
        middlename2 = new citibob.swing.typed.JTypedTextField();
        lastname2 = new citibob.swing.typed.JTypedTextField();
        dob = new citibob.swing.typed.JTypedDateChooser();
        jLabel17 = new javax.swing.JLabel();
        gender = new citibob.swing.typed.JKeyedComboBox();
        lGender = new javax.swing.JLabel();
        jBoolCheckbox1 = new citibob.swing.typed.JBoolCheckbox();

        setMinimumSize(new java.awt.Dimension(135, 120));
        setPreferredSize(new java.awt.Dimension(174, 120));
        setLayout(new java.awt.BorderLayout());

        StudentPane.setMinimumSize(new java.awt.Dimension(135, 105));
        StudentPane.setPreferredSize(new java.awt.Dimension(174, 105));
        StudentPane.setLayout(new java.awt.GridBagLayout());

        FirstMiddleLast2.setLayout(new java.awt.GridBagLayout());

        lFirst2.setText("First"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FirstMiddleLast2.add(lFirst2, gridBagConstraints);

        lMiddle2.setText("Mid"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FirstMiddleLast2.add(lMiddle2, gridBagConstraints);

        lLast2.setText("Last"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        FirstMiddleLast2.add(lLast2, gridBagConstraints);

        salutation2.setColName("salutation"); // NOI18N
        salutation2.setPreferredSize(new java.awt.Dimension(40, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        FirstMiddleLast2.add(salutation2, gridBagConstraints);

        firstname2.setColName("firstname"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        FirstMiddleLast2.add(firstname2, gridBagConstraints);

        middlename2.setColName("middlename"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        FirstMiddleLast2.add(middlename2, gridBagConstraints);

        lastname2.setColName("lastname"); // NOI18N
        lastname2.setPreferredSize(new java.awt.Dimension(10, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        FirstMiddleLast2.add(lastname2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        StudentPane.add(FirstMiddleLast2, gridBagConstraints);

        dob.setColName("dob"); // NOI18N
        dob.setPreferredSize(new java.awt.Dimension(122, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 0);
        StudentPane.add(dob, gridBagConstraints);

        jLabel17.setText("DOB: "); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        StudentPane.add(jLabel17, gridBagConstraints);

        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gender.setColName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        StudentPane.add(gender, gridBagConstraints);

        lGender.setText("Gender: "); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        StudentPane.add(lGender, gridBagConstraints);

        jBoolCheckbox1.setText("(approx.)");
        jBoolCheckbox1.setColName("dobapprox");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        StudentPane.add(jBoolCheckbox1, gridBagConstraints);

        add(StudentPane, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FirstMiddleLast2;
    private javax.swing.JPanel StudentPane;
    private citibob.swing.typed.JTypedDateChooser dob;
    private citibob.swing.typed.JTypedTextField firstname2;
    private citibob.swing.typed.JKeyedComboBox gender;
    private citibob.swing.typed.JBoolCheckbox jBoolCheckbox1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel lFirst2;
    private javax.swing.JLabel lGender;
    private javax.swing.JLabel lLast2;
    private javax.swing.JLabel lMiddle2;
    private citibob.swing.typed.JTypedTextField lastname2;
    private citibob.swing.typed.JTypedTextField middlename2;
    private citibob.swing.typed.JTypedTextField salutation2;
    // End of variables declaration//GEN-END:variables
	
}
