/*
OffstageArts: Enterprise Database for Arts Organizations
This file Copyright (c) 2005-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * SchoolFrame.java
 *
 * Created on December 9, 2007, 4:45 PM
 */

package offstage.school.gui;

import citibob.sql.DbKeyedModel;
import citibob.sql.SqlRun;
import citibob.sql.UpdTasklet2;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import offstage.*;
import offstage.schema.TermidsSchema;

/**
 *
 * @author  citibob
 */
public class SchoolSetupFrame extends javax.swing.JFrame
{

FrontApp fapp;
SchoolModel schoolModel;

/** Creates new form SchoolFrame */
public SchoolSetupFrame()
{
	initComponents();
//	tabs.setSelectedComponent(regPanel);
}

public void initRuntime(SqlRun str, FrontApp xfapp)
//throws SQLException
{
	this.fapp = xfapp;

	this.schoolModel = new SchoolModel(str, fapp);
	
	coursesPanel.initRuntime(fapp, schoolModel, str);
	schedulePanel.initRuntime(fapp, schoolModel, str);
	termsAddPanel.initRuntime(fapp, schoolModel, str);
	discountPanel1.initRuntime(str, fapp);
//	this.courseListPanel.initRuntime(fapp, schoolModel, str);

	// Set up terms selector
//setKeyedModel selects the term --- but the KeyedModel is not getting filled in till afterwards
	final DbKeyedModel tkmodel = ((TermidsSchema)fapp.getSchema("termids")).currentTermsKmodel;
//			new DbKeyedModel(str, fapp.dbChange(), "termids",
//		"select groupid, name, null from termids where iscurrent order by firstdate desc");
	str.execUpdate(new UpdTasklet2() {
	public void run(SqlRun str) throws Exception {
		vTermID.addPropertyChangeListener("value", new PropertyChangeListener() {
		public void propertyChange(PropertyChangeEvent evt) {
			fapp.sqlRun().pushFlush();
			schoolModel.setTermID((Integer)(vTermID.getValue()));
			fapp.sqlRun().popFlush();		// Flush, conditional on no other items around us.
		}});
		vTermID.setKeyedModel(tkmodel, null);
//		if (tkmodel.size() > 0) vTermID.setSelectedIndex(0);
	}});

//	regPanel.initRuntime(str, xfapp, schoolModel);
	
//	str.execUpdate(new UpdTasklet2() {
//	public void run(SqlRun str) throws Exception {
//		// Also set up frame preferences
//		new citibob.swing.prefs.SwingPrefs().setPrefs(SchoolFrame.this, "", fapp.userRoot().node("SchoolFrame"));
//	}});

}

//int getTermID()
//{
//	Integer Termid = (Integer)vTermID.getValue();
//	return (Termid == null ? -1 : Termid);
//}



/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vTermID = new citibob.swing.typed.JKeyedComboBox();
        jLabel3 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        termsAddPanel = new offstage.school.gui.TermsAddPanel();
        schedulePanel = new offstage.school.gui.TermsPanel();
        coursesPanel = new offstage.school.gui.CoursesPanel();
        discountPanel1 = new offstage.openclass.DiscountPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mWindow = new javax.swing.JMenu();
        mHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("School Setup");

        vTermID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vTermID.setPreferredSize(new java.awt.Dimension(68, 19));

        jLabel3.setText("Term: ");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel3)
                .add(3, 3, 3)
                .add(vTermID, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel3)
            .add(vTermID, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        tabs.addTab("Terms", termsAddPanel);
        tabs.addTab("Calendar", schedulePanel);
        tabs.addTab("Courses", coursesPanel);
        tabs.addTab("Studio Discounts", discountPanel1);

        getContentPane().add(tabs, java.awt.BorderLayout.CENTER);

        mWindow.setText("Window");
        jMenuBar1.add(mWindow);

        mHelp.setText("Help");
        jMenuBar1.add(mHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private offstage.school.gui.CoursesPanel coursesPanel;
    private offstage.openclass.DiscountPanel discountPanel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mHelp;
    private javax.swing.JMenu mWindow;
    private offstage.school.gui.TermsPanel schedulePanel;
    private javax.swing.JTabbedPane tabs;
    private offstage.school.gui.TermsAddPanel termsAddPanel;
    private citibob.swing.typed.JKeyedComboBox vTermID;
    // End of variables declaration//GEN-END:variables

public static void showFrame(SqlRun str, final FrontApp fapp)
{
	final SchoolSetupFrame frame = new SchoolSetupFrame();
	frame.initRuntime(str, fapp);
	str.execUpdate(new UpdTasklet2() {
	public void run(SqlRun str) throws Exception {
		frame.setVisible(true);
	}});
}

	
}
