/*
OffstageArts: Enterprise Database for Arts Organizations
This file Copyright (c) 2005-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * StudentInfoPane.java
 *
 * Created on July 27, 2008, 10:02 PM
 */

package offstage.school.gui;

import citibob.sql.SqlRun;
import citibob.swing.typed.JKeyedComboBox;
import citibob.swing.typed.TypedWidgetBinder;
import offstage.FrontApp;
import offstage.schema.PersonsSchema;

/**
 *
 * @author  citibob
 */
public class StudentInfoPane extends ExtensiblePane {

	public void initRuntime(SqlRun str, FrontApp fapp, SchoolModel schoolModel) {}


	
	protected void bindGender(JKeyedComboBox gender, SchoolModel schoolModel)
	{
		gender.setKeyedModel(PersonsSchema.genderKmodel, null);
		new TypedWidgetBinder().bind(gender, schoolModel.studentRm,
				"gender", TypedWidgetBinder.BT_READWRITE);
		
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 91, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
	
}
