/*
OffstageArts: Enterprise Database for Arts Organizations
This file Copyright (c) 2005-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * CoursesPanel.java
 *
 * Created on December 15, 2007, 4:39 PM
 */

package offstage.school.gui;

import citibob.jschema.DbModel;
import citibob.jschema.IntKeyedDbModel;
import citibob.jschema.MultiDbModel;
import citibob.jschema.SchemaBufRowModel;
import citibob.jschema.SqlBufDbModel;
import citibob.task.SqlTask;
import citibob.task.ETask;
import citibob.sql.SqlRun;
import citibob.sql.UpdTasklet2;
import citibob.sql.pgsql.SqlInteger;
import citibob.swing.RowModel;
import citibob.swing.table.RowModelTableModel;
import offstage.FrontApp;
//import offstage.schema.DuedatesSchema;

/**
 *
 * @author  citibob
 */
public class TermsPanel extends javax.swing.JPanel
{
	
FrontApp fapp;
SchoolModel smod;

//SqlBufDbModel duedatesDm;
IntKeyedDbModel holidaysDm;

MultiDbModel allDm;

/** Creates new form CoursesPanel */
public TermsPanel()
{
	initComponents();
}

	

/** Creates new form CompleteStatusPanel */
public void initRuntime(FrontApp xfapp, SchoolModel xsmod, SqlRun str)
//throws SQLException
{
	this.fapp = xfapp;
	this.smod = xsmod;
	
//	ddType.setKeyedModel(((DuedatesSchema)fapp.getSchema("duedates")).kmodel);
	templatesPanel.initRuntime(str, fapp, smod, "school_termids");
	
	smod.addListener(new SchoolModel.Adapter() {
    public void termIDChanged(int oldTermID, int termID) {
			termChanged(fapp.sqlRun());
	}});
	
	termInfo.setSwingerMap(fapp.swingerMap());
	termInfo.setModel(new RowModelTableModel(smod.oneTermRm,
		new String[] {"Name", "Type", "From", "To (+1)", "Tuition Plans", "Current?"},
		new String[] {"name", "termtypeid", "firstdate", "nextdate", "rbplansetclass", "iscurrent"}));

	
//	// Due Dates
//	duedatesDm = new SqlBufDbModel(str, fapp,
//		new String[] {"duedates", "duedateids"},
//		null, //new String[] {"termid"},		// Set up when setKey() is called
//		new String[] {"duedates"}) {
//		public String getSelectSql(boolean proto) {
//			return
//				" select dd.*,id.name,id.description" +
//				" from duedates dd, duedateids id" +
//				" where dd.duedateid = id.duedateid" +
//				" and dd.termid = " + SqlInteger.sql(proto ? -1 : smod.getTermID());
//		}};
//	str.execUpdate(new UpdTasklet2() {
//	public void run(SqlRun str) throws Exception {
//		duedates.setModelU(duedatesDm.getSchemaBuf(),
//			new String[] {"Status", "Due Date", "Description"},
//			new String[] {"__status__", "duedate", "description"},
//			new boolean[] {false,true,false}, fapp.swingerMap());		
//	}});
	
	holidaysDm = new IntKeyedDbModel(fapp.getSchema("holidays"),
		"termid", fapp.dbChange()); //, new IntKeyedDbModel.Params(false));
	holidaysDm.setWhereClause("entityid = 0");
	holidaysDm.setDoInsertKeys(false);
	holidays.setModelU(holidaysDm.getSchemaBuf(),
		new String[] {"Status", "First Day", "Last Day", "Description"},
		new String[] {"__status__", "firstday", "lastday", "description"},
		null, fapp.swingerMap());
	
	allDm = new MultiDbModel(new DbModel[] {smod.oneTermDm, holidaysDm});
}

void termChanged(SqlRun str) 
{
	Integer Termid = (Integer)smod.getTermID();
	allDm.doUpdate(str);
	allDm.setKey(Termid);
	allDm.doSelect(str);
//	termInfo.revalidate();
//	termInfo.repaint();		// Needed because JTable without a JScrollPane
}

	
void all_doSelect(SqlRun str)
{
	allDm.doSelect(str);
}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jToolBar1 = new javax.swing.JToolBar();
        bSave = new javax.swing.JButton();
        bUndo = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        holidaysPane = new javax.swing.JScrollPane();
        holidays = new citibob.jschema.swing.SchemaBufTable();
        lHolidays = new javax.swing.JLabel();
        holidaysButtons = new javax.swing.JPanel();
        holAdd = new javax.swing.JButton();
        holDel = new javax.swing.JButton();
        holUndel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        termInfo = new citibob.swing.JTypeTable();
        lDueDate = new javax.swing.JLabel();
        lTermInfo = new javax.swing.JLabel();
        templatesPanel = new offstage.school.gui.TemplatesPanel();

        setLayout(new java.awt.BorderLayout());

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(bSave);

        bUndo.setText("Undo");
        bUndo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bUndoActionPerformed(evt);
            }
        });
        jToolBar1.add(bUndo);

        add(jToolBar1, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        holidaysPane.setEnabled(false);
        holidaysPane.setPreferredSize(new java.awt.Dimension(300, 275));

        holidays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        holidaysPane.setViewportView(holidays);

        jPanel3.add(holidaysPane, java.awt.BorderLayout.CENTER);

        lHolidays.setText("Holidays");
        jPanel3.add(lHolidays, java.awt.BorderLayout.NORTH);

        holAdd.setText("Add");
        holAdd.setMargin(new java.awt.Insets(2, 2, 2, 2));
        holAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                holAddActionPerformed(evt);
            }
        });
        holidaysButtons.add(holAdd);

        holDel.setText("Del");
        holDel.setMargin(new java.awt.Insets(2, 2, 2, 2));
        holDel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                holDelActionPerformed(evt);
            }
        });
        holidaysButtons.add(holDel);

        holUndel.setText("(Undo)");
        holUndel.setMargin(new java.awt.Insets(2, 2, 2, 2));
        holUndel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                holUndelActionPerformed(evt);
            }
        });
        holidaysButtons.add(holUndel);

        jPanel3.add(holidaysButtons, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setRightComponent(jPanel3);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        termInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        jPanel2.add(termInfo, gridBagConstraints);

        lDueDate.setText("Templates");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(lDueDate, gridBagConstraints);

        lTermInfo.setText("Term Parameters");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(lTermInfo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(templatesPanel, gridBagConstraints);

        jSplitPane1.setLeftComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void holUndelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_holUndelActionPerformed
	{//GEN-HEADEREND:event_holUndelActionPerformed
		fapp.guiRun().run(TermsPanel.this, new ETask() {
		public void run() throws Exception {
			holidaysDm.getSchemaBuf().undeleteRow(holidays.getSelectedRow());
			holidays.requestFocus();
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_holUndelActionPerformed

	private void bUndoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bUndoActionPerformed
	{//GEN-HEADEREND:event_bUndoActionPerformed
		fapp.guiRun().run(new SqlTask() {
		public void run(SqlRun str) throws Exception {
			all_doSelect(str);
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_bUndoActionPerformed

	private void bSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bSaveActionPerformed
	{//GEN-HEADEREND:event_bSaveActionPerformed
		fapp.guiRun().run(new SqlTask() {
		public void run(SqlRun str) throws Exception {
			allDm.doUpdate(str);
			str.flush();
			all_doSelect(str);
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_bSaveActionPerformed

	private void holDelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_holDelActionPerformed
	{//GEN-HEADEREND:event_holDelActionPerformed
		fapp.guiRun().run(TermsPanel.this, new ETask() {
		public void run() throws Exception {
			holidaysDm.getSchemaBuf().deleteRow(holidays.getSelectedRow());
			holidays.requestFocus();
		}});
	}//GEN-LAST:event_holDelActionPerformed

	private void holAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_holAddActionPerformed
	{//GEN-HEADEREND:event_holAddActionPerformed
		fapp.guiRun().run(TermsPanel.this, new SqlTask() {
		public void run(SqlRun str) throws Exception {
			holidaysDm.getSchemaBuf().insertRow(-1, "termid", (Integer)smod.getTermID());
		}});
// TODO add your handling code here:
	}//GEN-LAST:event_holAddActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSave;
    private javax.swing.JButton bUndo;
    private javax.swing.JButton holAdd;
    private javax.swing.JButton holDel;
    private javax.swing.JButton holUndel;
    private citibob.jschema.swing.SchemaBufTable holidays;
    private javax.swing.JPanel holidaysButtons;
    private javax.swing.JScrollPane holidaysPane;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lDueDate;
    private javax.swing.JLabel lHolidays;
    private javax.swing.JLabel lTermInfo;
    private offstage.school.gui.TemplatesPanel templatesPanel;
    private citibob.swing.JTypeTable termInfo;
    // End of variables declaration//GEN-END:variables
	
}
