/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MergeDialog.java
 *
 * Created on Dec 17, 2009, 9:40:28 PM
 */

package offstage.cleanse;

import citibob.sql.SqlRun;
import citibob.task.SqlTask;
import offstage.FrontApp;

/**
 *
 * @author citibob
 */
public class MergeDialog extends javax.swing.JDialog {

FrontApp app;
MergeModel mergeDm;

    /** Creates new form MergeDialog */
    public MergeDialog(SqlRun str, FrontApp fapp, java.awt.Frame parent) {
        super(parent, true);
        initComponents();

		this.app = fapp;
		app.setUserPrefs(this);
		mergePane.initRuntime(str, fapp);

		mergeDm = mergePane.getMergeDm();
		str.flush();
	}

	/** @return ID of remaining merged record.  NULL if nothing was done. */
	public Integer getMergedID()
		{ return mergePane.getMergedID(); }

	public void setEntityIDs(SqlRun str, int entityid0, int entityid1)
	{
		mergeDm.setEntityID(0, entityid0);
		mergeDm.setEntityID(1, entityid1);
		mergePane.refresh(str);
		str.flush();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mergePane = new offstage.cleanse.MergePane();
        controls = new javax.swing.JPanel();
        bMergeTo0 = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        bMergeTo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().add(mergePane, java.awt.BorderLayout.CENTER);

        bMergeTo0.setText("<- Merge");
        bMergeTo0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMergeTo0ActionPerformed(evt);
            }
        });
        controls.add(bMergeTo0);

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        controls.add(bCancel);

        bMergeTo1.setText("Merge ->");
        bMergeTo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMergeTo1ActionPerformed(evt);
            }
        });
        controls.add(bMergeTo1);

        getContentPane().add(controls, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void bMergeTo0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMergeTo0ActionPerformed
		app.guiRun().run(MergeDialog.this, new SqlTask() {
		public void run(SqlRun str) throws Exception {
			if (mergePane.doAction(str, MergeActions.M_REGULAR, MergeActions.MC_MERGE_TO_0)) {
				setVisible(false);
			}
		}});
}//GEN-LAST:event_bMergeTo0ActionPerformed

	private void bMergeTo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMergeTo1ActionPerformed
		app.guiRun().run(MergeDialog.this, new SqlTask() {
		public void run(SqlRun str) throws Exception {
			if (mergePane.doAction(str, MergeActions.M_REGULAR, MergeActions.MC_MERGE_TO_1)) {
				setVisible(false);
			}
		}});
}//GEN-LAST:event_bMergeTo1ActionPerformed

	private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
		setVisible(false);
		// TODO add your handling code here:
}//GEN-LAST:event_bCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bMergeTo0;
    private javax.swing.JButton bMergeTo1;
    private javax.swing.JPanel controls;
    private offstage.cleanse.MergePane mergePane;
    // End of variables declaration//GEN-END:variables

}
