/*
OffstageArts: Enterprise Database for Arts Organizations
This file Copyright (c) 2005-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * DiscountPanel.java
 *
 * Created on June 10, 2008, 10:47 PM
 */

package offstage.openclass;

import citibob.app.App;
import citibob.sql.SqlRun;
import citibob.sql.UpdTasklet2;
import citibob.task.SqlTask;
import offstage.FrontApp;

/**
 *
 * @author  citibob
 */
public class DiscountPanel extends javax.swing.JPanel {
	
App app;
OCDiscModels ocDiscModels;

	/** Creates new form DiscountPanel */
	public DiscountPanel() {
		initComponents();
	}

	public void initRuntime(SqlRun str, final FrontApp xapp)
	{
		ocDiscModels = new OCDiscModels(str, xapp);
		str.execUpdate(new UpdTasklet2() {
		public void run(SqlRun str) {
			oCDiscPanel.initRuntime(xapp, ocDiscModels);
			oCDiscPanel.refresh(str, null);
		}});
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oCDiscPanel = new offstage.openclass.OCDiscPane();
        jToolBar1 = new javax.swing.JToolBar();
        bSave = new javax.swing.JButton();
        bUndo = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());
        add(oCDiscPanel, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        bSave.setText("Save");
        bSave.setFocusable(false);
        bSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(bSave);

        bUndo.setText("Undo");
        bUndo.setFocusable(false);
        bUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUndoActionPerformed(evt);
            }
        });
        jToolBar1.add(bUndo);

        add(jToolBar1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

	private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
		app.guiRun().run(DiscountPanel.this, new SqlTask() {
			public void run(SqlRun str) throws Exception {
				ocDiscModels.getDm().doUpdate(str);
				ocDiscModels.getDm().doSelect(str);
			}});
			// TODO add your handling code here:
	}//GEN-LAST:event_bSaveActionPerformed

	private void bUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUndoActionPerformed
		app.guiRun().run(DiscountPanel.this, new SqlTask() {
			public void run(SqlRun str) throws Exception {
				ocDiscModels.getDm().doSelect(str);
			}});
			// TODO add your handling code here:
	}//GEN-LAST:event_bUndoActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSave;
    private javax.swing.JButton bUndo;
    private javax.swing.JToolBar jToolBar1;
    private offstage.openclass.OCDiscPane oCDiscPanel;
    // End of variables declaration//GEN-END:variables
	
}
