/*
OffstageArts: Enterprise Database for Arts Organizations
This file Copyright (c) 2005-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * FrontDeskFrame.java
 *
 * Created on April 13, 2008, 4:46 PM
 */

package offstage.frontdesk;

import citibob.sql.SqlRun;
import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import offstage.FrontApp;

/**
 
 @author  citibob
 */
public class FrontDeskFrame extends javax.swing.JFrame
{
	class CatchCCAction extends AbstractAction {
            public CatchCCAction(String text) {
                super(text);
            }

            public void actionPerformed(ActionEvent e) {
                System.out.println("Action [" + e.getActionCommand() + "] performed!");
            }

        }
	/** Creates new form FrontDeskFrame */
	public FrontDeskFrame()
	{
		initComponents();
		setTitle("Front Desk");
	}
	
	public void initRuntime(SqlRun str, FrontApp app)
	{
		this.openClassPanel1.initRuntime(str, app);
		openRegPanel1.initRuntime(str, app);
                
                CatchCCAction CatchCC = new CatchCCAction("stuff");                

                jTabbedPane1.getInputMap(JComponent.WHEN_FOCUSED).put(KeyStroke.getKeyStroke("typed %"), "catchcc");
                jTabbedPane1.getActionMap().put("catchcc", CatchCC);
               
        }
    	
	/** This method is called from within the constructor to
	 initialize the form.
	 WARNING: Do NOT modify this code. The content of this method is
	 always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        openRegPanel1 = new offstage.frontdesk.OpenRegPanel();
        openClassPanel1 = new offstage.frontdesk.OpenClassPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Front Desk");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addTab("Registration", openRegPanel1);
        jTabbedPane1.addTab("Sign-In", openClassPanel1);

        jPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Window");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	/**
	 @param args the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new FrontDeskFrame().setVisible(true);
			}
		});
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private offstage.frontdesk.OpenClassPanel openClassPanel1;
    private offstage.frontdesk.OpenRegPanel openRegPanel1;
    // End of variables declaration//GEN-END:variables
	
}
