/*
OffstageArts: Enterprise Database for Arts Organizations
This file Copyright (c) 2005-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * OpenRegPanel.java
 *
 * Created on June 8, 2008, 3:30 PM
 */

package offstage.frontdesk;

import citibob.jschema.DbModel;
import citibob.sql.SqlRun;
import citibob.swing.typed.SwingerMap;
import citibob.task.SqlTask;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import offstage.FrontApp;

/**
 *
 * @author  citibob
 */
public class OpenRegPanel extends javax.swing.JPanel {

FrontApp app;
DbModel personDm;

/** Creates new form OpenRegPanel */
	public OpenRegPanel() {
		initComponents();
	}

	public void initRuntime(SqlRun str, final FrontApp xapp)
	{
		this.app = xapp;
		SwingerMap smap = xapp.swingerMap();
		personPanel.initRuntime(str, xapp);
		personDm = personPanel.dmod;
//		searchPanel.initRuntime(xapp, personDm);
		
		// Change entity when a person is selected.
		selector.initRuntime(app);
		selector.setAutoSelectOnOne(true);
		selector.addPropertyChangeListener("value", new PropertyChangeListener() {
		public void propertyChange(PropertyChangeEvent evt) {
			Integer entityid = (Integer)evt.getNewValue();
			if (entityid == null) return;
			
			SqlRun str = app.sqlRun();
			str.pushFlush();
				personDm.setKey(entityid);
				personDm.doSelect(str);
			str.popFlush();
		}});

	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        personPanel = new offstage.frontdesk.FDPersonPanel();
        selector = new offstage.swing.typed.EntitySelector();
        jToolBar1 = new javax.swing.JToolBar();
        bSavePerson = new javax.swing.JButton();
        bUndoPerson = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setLeftComponent(personPanel);
        jSplitPane1.setBottomComponent(selector);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        bSavePerson.setText("Save");
        bSavePerson.setFocusable(false);
        bSavePerson.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bSavePerson.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bSavePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSavePersonActionPerformed(evt);
            }
        });
        jToolBar1.add(bSavePerson);

        bUndoPerson.setText("Undo");
        bUndoPerson.setFocusable(false);
        bUndoPerson.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bUndoPerson.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bUndoPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUndoPersonActionPerformed(evt);
            }
        });
        jToolBar1.add(bUndoPerson);

        add(jToolBar1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

	private void bSavePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSavePersonActionPerformed
		app.guiRun().run(this, new SqlTask() {
			public void run(SqlRun str) throws Exception {
				personDm.doUpdate(str);
				personDm.doSelect(str);
			}});
	}//GEN-LAST:event_bSavePersonActionPerformed

	private void bUndoPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUndoPersonActionPerformed
		app.guiRun().run(this, new SqlTask() {
			public void run(SqlRun str) throws Exception {
				personDm.doSelect(str);
			}});
	}//GEN-LAST:event_bUndoPersonActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSavePerson;
    private javax.swing.JButton bUndoPerson;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private offstage.frontdesk.FDPersonPanel personPanel;
    private offstage.swing.typed.EntitySelector selector;
    // End of variables declaration//GEN-END:variables
	
}
