/*
OffstageArts: Enterprise Database for Arts Organizations
This file Copyright (c) 2005-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * DupCheckPanel.java
 *
 * Created on October 12, 2006, 8:31 PM
 */

package offstage.wizards.newrecord;

import offstage.db.*;
import citibob.task.*;
import java.sql.*;
import citibob.swing.*;
import citibob.swing.table.*;
import citibob.app.*;
import citibob.sql.*;
import citibob.swing.typed.SingleSelectStyledTable;
import offstage.FrontApp;
import offstage.devel.gui.DevelModel;

/**
 *
 * @author  citibob
 */
public class IDListViewer extends javax.swing.JPanel {

DevelModel entityDb;
EntityListTableModel dupsModel;

/** Creates new form DupCheckPanel */
public IDListViewer() {
	initComponents();
}

//public void initRuntime(SqlRun str,
//EntityListTableModel dupsModel, DevelModel entityDb,
//ActionRunner guiRunner, SwingerMap smap)
//{
//	this.dupsModel = dupsModel;
//	this.entityDb = entityDb;
//}

public void initRuntime(SqlRun str,
DevelModel xentityDb,
String idSql, String orderBy,
final FrontApp app)
//final ActionRunner guiRunner, SwingerMap smap)
throws SQLException
{
//	final App app = xapp;
//	final ActionRunner guiRunner = app.getGuiRunner();
	dupsModel = new EntityListTableModel(app.sqlTypeSet());
	dupsModel.setIdSql(idSql, orderBy);
	dupsModel.executeQuery(str);
	
	this.entityDb = xentityDb;
	dupsTable.initRuntime(dupsModel);
	mainEntityPanel.initRuntime(str, app, entityDb);
	DClickTableMouseListener dclick =
		new DClickTableMouseListener(dupsTable) {
		public void doubleClicked(final int row) {
			app.guiRun().run(IDListViewer.this, new SqlTask() {
			public void run(SqlRun str) throws Exception {
				// Make sure it's selected in the GUI
				dupsTable.getSelectionModel().setSelectionInterval(row, row);

				// Process the selection
				int entityid = getSelectedEntityID(dupsTable);
				if (entityid < 0) return;
				entityDb.setKey(entityid);
				entityDb.doSelect(str);
			}});
		}};
	
	// Double-clicking will go to selected person
	dupsTable.addMouseListener(dclick);
	dclick.doubleClicked(0);		// There's at least one row here, select it.

}

int getSelectedEntityID(SingleSelectStyledTable searchResultsTable)
{
	int selected = searchResultsTable.getSelectedRow();
	if (selected < 0) return -1;
	int entityID = dupsModel.getEntityID(selected);
	return entityID;
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        dupsTable = new offstage.gui.FamilyTable();
        mainEntityPanel = new offstage.devel.gui.PersonPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane2.setDividerLocation(200);
        dupsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dupsTable);

        jSplitPane2.setLeftComponent(jScrollPane1);

        jSplitPane2.setRightComponent(mainEntityPanel);

        add(jSplitPane2, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private offstage.gui.FamilyTable dupsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private offstage.devel.gui.PersonPanel mainEntityPanel;
    // End of variables declaration//GEN-END:variables

}
